nginx:
  build: infra/nginx
  command: nginx -g "daemon off;"
  links:
    - php-main
  ports:
    - "8080:80"
  volumes:
    - ./peguepague/public:/var/www/html/app/public

php-main:
  build: infra/php
  volumes:
    - .:/var/www/html
  working_dir: /var/www/html/peguepague/public
  command: php-fpm
  links:
    - db
    - redis
  ports:
    - "9000:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: ${DB_DATABASE}
    DB_USERNAME: ${DB_USERNAME}
    DB_PASSWORD: ${DB_PASSWORD}
    CACHE_DRIVER: file
    QUEUE_CONNECTION: redis
    REDIS_HOST: redis
    REDIS_PORT: 6379
    MOCK_AUTHORIZER_URL: https://run.mocky.io/v3/8fafdd68-a090-496f-8c9a-3442cf30dae6
    MOCK_NOTIFIER_URL: https://run.mocky.io/v3/b19f7b9f-9cbf-4fc6-ad22-dc30601aec04

php-worker:
  build: infra/php
  volumes:
    - .:/var/www/html
  working_dir: /var/www/html/peguepague
  command: php artisan queue:work
  links:
    - db
    - redis
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: ${DB_DATABASE}
    DB_USERNAME: ${DB_USERNAME}
    DB_PASSWORD: ${DB_PASSWORD}
    CACHE_DRIVER: file
    QUEUE_CONNECTION: redis
    REDIS_HOST: redis
    REDIS_PORT: 6379
    MOCK_AUTHORIZER_URL: https://run.mocky.io/v3/8fafdd68-a090-496f-8c9a-3442cf30dae6
    MOCK_NOTIFIER_URL: https://run.mocky.io/v3/b19f7b9f-9cbf-4fc6-ad22-dc30601aec04

db:
  image: mysql:8
  command: --default-authentication-plugin=mysql_native_password
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USERNAME}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}

redis:
  image: redis:alpine
  ports:
    - "6379:6379"